---
kind: pipeline
name: build

platform:
  os: linux

steps:
- name: docker
  image: plugins/docker:19
  settings:
    repo: ghcr.io/euronetzrt/django
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
